---20151231定期贵宾
insert into ccc select  b.zh, yehz,yg,a.khbh from  ( select khbh ,  max(ye) yg , sum(ye)  yehz from d_ds_fhzxx  where rq = to_date('20151231','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grdq') group by khbh   having sum(ye)/10000 >= 100   ) a , d_ds_fhzxx b where b.rq = to_date('20151231','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grdq') and a.khbh = b.khbh and yg = ye;
insert into ccc select  b.zh, yehz,yg,a.khbh from  ( select khbh ,  max(ye) yg , sum(ye)  yehz from d_ds_fhzxx  where rq = to_date('20151231','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grdq') group by khbh   having sum(ye)/10000 >= 20 and sum(ye)/10000 < 50   ) a , d_ds_fhzxx b where b.rq = to_date('20151231','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grdq') and a.khbh = b.khbh and yg = ye;
insert into ccc select  b.zh, yehz,yg,a.khbh from  ( select khbh ,  max(ye) yg , sum(ye)  yehz from d_ds_fhzxx  where rq = to_date('20151231','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grdq') group by khbh   having sum(ye)/10000 >= 50 and sum(ye)/10000 < 100   ) a , d_ds_fhzxx b where b.rq = to_date('20151231','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grdq') and a.khbh = b.khbh and yg = ye;

---20151231活期贵宾
insert into ccc select  b.zh, yehz,yg,a.khbh from  ( select khbh ,  max(ye) yg , sum(ye)  yehz from d_ds_fhzxx  where rq = to_date('20151231','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grhq') group by khbh   having sum(ye)/10000 >= 100   ) a , d_ds_fhzxx b where b.rq = to_date('20151231','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grhq') and a.khbh = b.khbh and yg = ye;
insert into ccc select  b.zh, yehz,yg,a.khbh from  ( select khbh ,  max(ye) yg , sum(ye)  yehz from d_ds_fhzxx  where rq = to_date('20151231','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grhq') group by khbh   having sum(ye)/10000 >= 20 and sum(ye)/10000 < 50   ) a , d_ds_fhzxx b where b.rq = to_date('20151231','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grhq') and a.khbh = b.khbh and yg = ye;
insert into ccc select  b.zh, yehz,yg,a.khbh from  ( select khbh ,  max(ye) yg , sum(ye)  yehz from d_ds_fhzxx  where rq = to_date('20151231','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grhq') group by khbh   having sum(ye)/10000 >= 50 and sum(ye)/10000 < 100   ) a , d_ds_fhzxx b where b.rq = to_date('20151231','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grhq') and a.khbh = b.khbh and yg = ye;

---20160331 定期贵宾
insert into ccc select  b.zh, yehz,yg,a.khbh from  ( select khbh ,  max(ye) yg , sum(ye)  yehz from d_ds_fhzxx  where rq = to_date('20160331','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grdh') group by khbh   having sum(ye)/10000 >= 100  ) a , d_ds_fhzxx b where b.rq = to_date('20160331','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grdh') and a.khbh = b.khbh and yg = ye;
insert into ccc select  b.zh, yehz,yg,a.khbh from  ( select khbh ,  max(ye) yg , sum(ye)  yehz from d_ds_fhzxx  where rq = to_date('20160331','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grdh') group by khbh   having sum(ye)/10000 >= 20 and sum(ye)/10000 < 50   ) a , d_ds_fhzxx b where b.rq = to_date('20160331','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grdh') and a.khbh = b.khbh and yg = ye;
insert into ccc select  b.zh, yehz,yg,a.khbh from  ( select khbh ,  max(ye) yg , sum(ye)  yehz from d_ds_fhzxx  where rq = to_date('20160331','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grdh') group by khbh   having sum(ye)/10000 >= 50 and sum(ye)/10000 < 100   ) a , d_ds_fhzxx b where b.rq = to_date('20160331','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grdh') and a.khbh = b.khbh and yg = ye;

---20160331 活期贵宾

insert into ccc select  b.zh, yehz,yg,a.khbh from  ( select khbh ,  max(ye) yg , sum(ye)  yehz from d_ds_fhzxx  where rq = to_date('20160331','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grhq') group by khbh   having sum(ye)/10000 >= 100  ) a , d_ds_fhzxx b where b.rq = to_date('20160331','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grhq') and a.khbh = b.khbh and yg = ye;
insert into ccc select  b.zh, yehz,yg,a.khbh from  ( select khbh ,  max(ye) yg , sum(ye)  yehz from d_ds_fhzxx  where rq = to_date('20160331','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grhq') group by khbh   having sum(ye)/10000 >= 20 and sum(ye)/10000 < 50   ) a , d_ds_fhzxx b where b.rq = to_date('20160331','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grhq') and a.khbh = b.khbh and yg = ye;
insert into ccc select  b.zh, yehz,yg,a.khbh from  ( select khbh ,  max(ye) yg , sum(ye)  yehz from d_ds_fhzxx  where rq = to_date('20160331','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grhq') group by khbh   having sum(ye)/10000 >= 50 and sum(ye)/10000 < 100   ) a , d_ds_fhzxx b where b.rq = to_date('20160331','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grhq') and a.khbh = b.khbh and yg = ye;

---20151231,20160331 定活期有效户
insert into ccc select  b.zh, yehz,yg,a.khbh from  ( select khbh ,  max(ye) yg , sum(ye)  yehz from d_ds_fhzxx  where rq = to_date('20151231','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grhq') group by khbh   having sum(ye) >= 1000  ) a , d_ds_fhzxx b where b.rq = to_date('20151231','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grhq') and a.khbh = b.khbh and yg = ye;
insert into ccc select  b.zh, yehz,yg,a.khbh from  ( select khbh ,  max(ye) yg , sum(ye)  yehz from d_ds_fhzxx  where rq = to_date('20160331','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grhq') group by khbh   having sum(ye) >= 1000  ) a , d_ds_fhzxx b where b.rq = to_date('20160331','yyyymmdd') and trim(kmh) in (select trim(tjdm) from d_sum_code where sjdm = 'grhq') and a.khbh = b.khbh and yg = ye;

---
select zgmc,name,count(*) from d_user_account_change a , d_user_change b ,b_m_sys_bran , ccc c  where   b.ksrq <= to_date('20151231','yyyymmdd') and b.jsrq >= to_date('20151231','yyyymmdd') and a.ksrq <= to_date('20151231','yyyymmdd') and a.jsrq >= to_date('20151231','yyyymmdd') and a.zgbh = b.zgbh  and bmdm = code  and a.zh = c.zh  group by zgmc , name  order by name
select zgmc,name,count(*) from d_user_account_change a , d_user_change b ,b_m_sys_bran , ccc c  where   b.ksrq <= to_date('20160331','yyyymmdd') and b.jsrq >= to_date('20160331','yyyymmdd') and a.ksrq <= to_date('20160331','yyyymmdd') and a.jsrq >= to_date('20160331','yyyymmdd') and a.zgbh = b.zgbh  and bmdm = code  and a.zh = c.zh  group by zgmc , name  order by name
select zgmc,name,count(*) from d_user_account_change a , d_user_change b ,b_m_sys_bran , ccc c  where   b.ksrq <= to_date('20151231','yyyymmdd') and b.jsrq >= to_date('20151231','yyyymmdd') and a.ksrq <= to_date('20151231','yyyymmdd') and a.jsrq >= to_date('20151231','yyyymmdd') and a.zgbh = b.zgbh  and bmdm = code  and a.zh = c.zh  group by zgmc , name
select zgmc,name,count(*) from d_user_account_change a , d_user_change b ,b_m_sys_bran , ccc c  where   b.ksrq <= to_date('20151231','yyyymmdd') and b.jsrq >= to_date('20151231','yyyymmdd') and a.ksrq <= to_date('20151231','yyyymmdd') and a.jsrq >= to_date('20151231','yyyymmdd') and a.zgbh = b.zgbh  and bmdm = code  and a.zh = c.zh  group by zgmc , name  order by name
select zgmc,name,rjkmye from d_accman_year_rj  a , d_user_change b,b_m_sys_bran where tjdm = 'ndsck' and rq = to_date('20160331','yyyymmdd') and b.ksrq <= to_date('20160331','yyyymmdd') and b.jsrq >= to_date('20160331','yyyymmdd') and a.zgbh = b.zgbh  and bmdm = code  order by code
select zgmc,name,rjkmye from d_accman_year_rj  a , d_user_change b,b_m_sys_bran where tjdm = 'ndsck' and rq = to_date('20160331','yyyymmdd') and b.ksrq <= to_date('20160331','yyyymmdd') and b.jsrq >= to_date('20160331','yyyymmdd') and bmdm = code  order by code
